# Generated by Django 3.2.9 on 2021-12-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info_class_number', models.PositiveSmallIntegerField()),
                ('user_info_student_number', models.PositiveSmallIntegerField()),
                ('user_info_student_name', models.CharField(max_length=50)),
                ('user_info_body_temperature', models.CharField(max_length=10)),
                ('is_run_code', models.BooleanField(default=True)),
                ('user_info_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_info_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
