# Generated by Django 3.2.9 on 2021-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_username',
            field=models.CharField(max_length=150, verbose_name='line_username'),
        ),
    ]
