# Generated by Django 3.2.9 on 2021-12-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'ユーザー情報'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_run_code',
            field=models.IntegerField(choices=[(1, '実行する'), (0, '停止する')], verbose_name='実行するか'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_body_temperature',
            field=models.CharField(max_length=10, verbose_name='体温'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_class_number',
            field=models.PositiveSmallIntegerField(verbose_name='クラス番号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_student_name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_student_number',
            field=models.PositiveSmallIntegerField(verbose_name='出席番号'),
        ),
    ]
