# Generated by Django 3.2.9 on 2021-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_run_code',
            field=models.IntegerField(choices=[(1, '実行する'), (0, '停止する')], default=True, verbose_name='実行するか'),
        ),
    ]
